platform :ios, '8.0'
use_frameworks!

target 'Demo' do
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.6'  
pod 'SDAutoLayout', '~> 2.1.1'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 3.1.0'
pod 'IQKeyboardManager', '~> 4.0.3'
end
